import { pairedDemo } from '../style-gallery/district-demo.js';
import { build } from 'esbuild';
import { cp, mkdir, readFile, writeFile } from 'node:fs/promises';
await mkdir('docs/style-gallery', { recursive: true });
await cp('style-gallery', 'docs/style-gallery', { recursive: true });
for (const name of ['index.html', 'google-signin.js', '_headers', '_routes.json']) await cp(name, `docs/${name}`);
await cp('auth', 'docs/auth', { recursive: true });
await cp('server/comparison-core.js', 'docs/comparison-core.js');
await build({ entryPoints: ['server/worker.js'], outfile: 'docs/_worker.js', bundle: true, format: 'esm', platform: 'browser', target: 'es2022', conditions: ['workerd', 'worker', 'browser'] });
await mkdir('docs/vendor', { recursive: true });
for (const name of ['three.module.js', 'three.core.js']) await cp(`node_modules/three/build/${name}`, `docs/vendor/${name}`);
await cp('node_modules/three/examples/jsm/controls/OrbitControls.js', 'docs/vendor/OrbitControls.js');
await cp('node_modules/three/LICENSE', 'docs/vendor/THREE-LICENSE.txt');
const source = await readFile('style-gallery/structured-3d.html', 'utf8');
const auditLine = source.split('\n').find(line => line.startsWith('const AUDIT='));
if (!auditLine) throw new Error('The public demo fixture is missing');
const audit = pairedDemo(JSON.parse(auditLine.slice('const AUDIT='.length).replace(/;\s*$/, '')));
if (audit.meta.source_mode !== 'sample') throw new Error('Refusing to embed non-demo container data');
const template = await readFile('style-gallery/explorer.html', 'utf8');
await writeFile('docs/style-gallery/explorer.html', template.replace('const AUDIT={};', `const AUDIT=${JSON.stringify(audit).replaceAll('<', '\\u003c')};`));
console.log('Built gallery, sign-in, and private Worker with Clerk authentication.');
